-- ═══════════════════════════════════════════════════════════════════
-- Phase 6 通知域。版本号区间 V40-V49。
--
-- ★ 本迁移由 oa-notify-service 自己执行，用【独立的 Flyway 历史表】
--   （flyway_schema_history_notify）。理由：oa-app 不依赖 oa-notify-service，
--   这些 SQL 进不了 oa-app 的 classpath；而两个应用共用一张历史表会互相判对方的
--   迁移为"未知版本"。独立部署单元拥有自己的 schema 与自己的迁移史，边界才是干净的。
-- ═══════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS oa_notify;

-- ───────────────────────────────── 稠密收件人索引
-- RoaringBitmap 的下标是 int，而系统的主体标识是 Casdoor sub（UUID 字符串，ADR）。
-- 直接拿 employee.id 当下标是不行的：那是 oa_org 的东西，跨 schema join 被明令禁止，
-- 而且通知服务也不该因为组织域改了主键类型就跟着改。
-- 所以通知域维护自己的一份稠密映射：谁第一次成为收件人，就分配一个自增序号。
CREATE TABLE oa_notify.recipient (
    seq        integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  bigint      NOT NULL DEFAULT 1,
    user_id    varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_recipient_user UNIQUE (tenant_id, user_id)
);

-- ───────────────────────────────── 站内信（按月分区）
-- 容量（FINAL_PLAN §9.2 / R10）：万人 × 日均若干条 ≈ 5,000 万/年。
-- 分区让"归档三个月前"变成 DETACH（秒级），而不是一条会拖垮线上的 DELETE。
CREATE TABLE oa_notify.notification (
    id         bigserial    NOT NULL,
    tenant_id  bigint       NOT NULL DEFAULT 1,
    user_id    varchar(64)  NOT NULL,
    category   varchar(16)  NOT NULL,          -- TODO | ANNOUNCEMENT | SYSTEM
    title      varchar(200) NOT NULL,
    content    text,
    biz_type   varchar(32),
    biz_id     varchar(64),
    link       varchar(512),
    -- 幂等键：同一业务事件重复投递（Kafka 至少一次）不该产生两条站内信
    dedup_key  varchar(128),
    read_at    timestamptz,
    created_at timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at),
    CONSTRAINT ck_notify_category CHECK (category IN ('TODO','ANNOUNCEMENT','SYSTEM'))
) PARTITION BY RANGE (created_at);

-- 未读列表是最热的查询：按人 + 未读 + 倒序。分区表索引会在各分区上分别建。
CREATE INDEX ix_notification_user_unread ON oa_notify.notification(user_id, created_at DESC)
    WHERE read_at IS NULL;
CREATE INDEX ix_notification_user ON oa_notify.notification(user_id, created_at DESC);
-- 幂等唯一索引必须带分区键；dedup_key 为空的（如手工发的）不参与去重
CREATE UNIQUE INDEX uk_notification_dedup ON oa_notify.notification(tenant_id, user_id, dedup_key, created_at)
    WHERE dedup_key IS NOT NULL;

DO $$
DECLARE d date := date_trunc('month', current_date)::date; i int;
BEGIN
    FOR i IN 0..11 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS oa_notify.notification_%s PARTITION OF oa_notify.notification
             FOR VALUES FROM (%L) TO (%L)',
            to_char(d + (i || ' month')::interval, 'YYYYMM'),
            (d + (i || ' month')::interval)::date,
            (d + ((i + 1) || ' month')::interval)::date);
    END LOOP;
END $$;
CREATE TABLE IF NOT EXISTS oa_notify.notification_default PARTITION OF oa_notify.notification DEFAULT;

-- ───────────────────────────────── 公告
CREATE TABLE oa_notify.announcement (
    id            bigserial    PRIMARY KEY,
    tenant_id     bigint       NOT NULL DEFAULT 1,
    title         varchar(200) NOT NULL,
    content       text         NOT NULL,
    publisher_id  varchar(64)  NOT NULL,
    publisher_name varchar(64),
    -- 受众【由发布方算好传进来】，通知域不解析组织结构：
    -- 谁该收是业务语义（要走数据权限、组织树、角色），怎么送才是通知域的事。
    -- 这与 ADR-0010"审批人由 OA 侧算好塞进流程变量"是同一条原则。
    audience_type varchar(16)  NOT NULL DEFAULT 'EXPLICIT',
    audience_count integer     NOT NULL DEFAULT 0,
    status        varchar(16)  NOT NULL DEFAULT 'PUBLISHED',   -- PUBLISHED | REVOKED
    published_at  timestamptz  NOT NULL DEFAULT now(),
    expire_at     timestamptz,
    CONSTRAINT ck_ann_status CHECK (status IN ('PUBLISHED','REVOKED'))
);
CREATE INDEX ix_announcement_published ON oa_notify.announcement(published_at DESC);

-- ───────────────────────────────── 已读回执：位图，不是明细表
-- 一条全员公告若按"每人一行"记回执，万人就是 10,000 行 × 每条公告。
-- 一年几百条公告 = 几百万行，只为回答"读了多少人"。
-- RoaringBitmap 把它压成一个 bytea：万人稠密位图约 1.3KB，验收线是 < 100KB。
-- 代价是失去了"谁在什么时刻读的"这个时间维度 —— 公告场景不需要，
-- 需要审计到人的场景（如合规签署）应另建明细表，不要复用这个。
CREATE TABLE oa_notify.announcement_read (
    announcement_id bigint      PRIMARY KEY REFERENCES oa_notify.announcement(id) ON DELETE CASCADE,
    bitmap          bytea       NOT NULL,
    read_count      integer     NOT NULL DEFAULT 0,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- 公告的受众位图（谁该收）。与已读位图做 AND/ANDNOT 就能算出"谁还没读"。
CREATE TABLE oa_notify.announcement_audience (
    announcement_id bigint      PRIMARY KEY REFERENCES oa_notify.announcement(id) ON DELETE CASCADE,
    bitmap          bytea       NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ───────────────────────────────── 多渠道投递日志
-- 只记非站内渠道（邮件/短信/企微/飞书）。站内信本身就是一张表，不必再记一遍。
CREATE TABLE oa_notify.channel_log (
    id          bigserial    PRIMARY KEY,
    tenant_id   bigint       NOT NULL DEFAULT 1,
    channel     varchar(16)  NOT NULL,          -- EMAIL | SMS | WECOM | FEISHU
    user_id     varchar(64)  NOT NULL,
    title       varchar(200),
    status      varchar(16)  NOT NULL,          -- SENT | FAILED | SKIPPED
    error       text,
    created_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_channel_log_created ON oa_notify.channel_log(created_at DESC);
