-- 审批域数据字典注释。

COMMENT ON TABLE oa_flow.form_template IS '版本化动态表单模板，历史单据固定引用提交时的模板版本';
COMMENT ON COLUMN oa_flow.form_template.id IS '表单模板主键';
COMMENT ON COLUMN oa_flow.form_template.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.form_template.code IS '表单模板业务编码';
COMMENT ON COLUMN oa_flow.form_template.name IS '表单模板名称';
COMMENT ON COLUMN oa_flow.form_template.version IS '同一模板编码下的版本号';
COMMENT ON COLUMN oa_flow.form_template.schema_json IS '描述字段、校验和组件的 JSON Schema';
COMMENT ON COLUMN oa_flow.form_template.status IS '模板状态：DRAFT、PUBLISHED 或 ARCHIVED';
COMMENT ON COLUMN oa_flow.form_template.published_at IS '模板发布时间';
COMMENT ON COLUMN oa_flow.form_template.created_by IS '创建人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.form_template.created_at IS '创建时间';

COMMENT ON TABLE oa_flow.approval_instance IS 'OA 侧审批实例与业务单据快照，关联外部 workflow-platform 实例';
COMMENT ON COLUMN oa_flow.approval_instance.id IS 'OA 审批实例主键';
COMMENT ON COLUMN oa_flow.approval_instance.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.approval_instance.biz_type IS '业务单据类型，如 LEAVE、REIMBURSE';
COMMENT ON COLUMN oa_flow.approval_instance.business_key IS '业务单据唯一标识';
COMMENT ON COLUMN oa_flow.approval_instance.process_definition_key IS 'workflow-platform 流程定义键';
COMMENT ON COLUMN oa_flow.approval_instance.process_instance_id IS 'workflow-platform 流程实例标识，由异步对账回填';
COMMENT ON COLUMN oa_flow.approval_instance.form_template_id IS '提交时使用的表单模板主键';
COMMENT ON COLUMN oa_flow.approval_instance.form_version IS '提交时使用的表单模板版本';
COMMENT ON COLUMN oa_flow.approval_instance.form_data IS '提交时冻结的表单数据 JSON';
COMMENT ON COLUMN oa_flow.approval_instance.applicant_user_id IS '申请人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.approval_instance.applicant_employee_id IS '申请人的员工内部主键';
COMMENT ON COLUMN oa_flow.approval_instance.applicant_name IS '申请人姓名快照';
COMMENT ON COLUMN oa_flow.approval_instance.org_id IS '申请发生时的组织主键快照';
COMMENT ON COLUMN oa_flow.approval_instance.org_path IS '申请发生时的组织物化路径快照，用于数据权限过滤';
COMMENT ON COLUMN oa_flow.approval_instance.approver_chain IS 'OA 侧计算并冻结的审批人链 JSON';
COMMENT ON COLUMN oa_flow.approval_instance.status IS '实例状态：SUBMITTED、RUNNING、FINISHED、CANCELLED 或 FAILED';
COMMENT ON COLUMN oa_flow.approval_instance.outcome IS '最终结果：APPROVED、REJECTED 或 CANCELLED';
COMMENT ON COLUMN oa_flow.approval_instance.submitted_at IS '提交时间';
COMMENT ON COLUMN oa_flow.approval_instance.finished_at IS '流程结束时间';
COMMENT ON COLUMN oa_flow.approval_instance.version IS '乐观锁版本号';

COMMENT ON TABLE oa_flow.approval_node_log IS '审批节点办理轨迹，记录实际操作人、代理身份和动作';
COMMENT ON COLUMN oa_flow.approval_node_log.id IS '节点轨迹主键';
COMMENT ON COLUMN oa_flow.approval_node_log.instance_id IS 'OA 审批实例主键';
COMMENT ON COLUMN oa_flow.approval_node_log.task_id IS 'workflow-platform 任务标识';
COMMENT ON COLUMN oa_flow.approval_node_log.node_key IS '流程节点定义键';
COMMENT ON COLUMN oa_flow.approval_node_log.node_name IS '流程节点名称';
COMMENT ON COLUMN oa_flow.approval_node_log.actor_user_id IS '实际办理人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.approval_node_log.on_behalf_of IS '代理办理时被代表人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.approval_node_log.action IS '办理动作：APPROVE、REJECT、TRANSFER 或 CC';
COMMENT ON COLUMN oa_flow.approval_node_log.comment IS '办理意见';
COMMENT ON COLUMN oa_flow.approval_node_log.acted_at IS '办理时间';

COMMENT ON TABLE oa_flow.todo_item IS '审批待办 CQRS 读模型，供工作台按处理人快速查询';
COMMENT ON COLUMN oa_flow.todo_item.id IS '待办读模型主键';
COMMENT ON COLUMN oa_flow.todo_item.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.todo_item.task_id IS 'workflow-platform 任务标识';
COMMENT ON COLUMN oa_flow.todo_item.process_instance_id IS 'workflow-platform 流程实例标识';
COMMENT ON COLUMN oa_flow.todo_item.instance_id IS 'OA 审批实例主键';
COMMENT ON COLUMN oa_flow.todo_item.biz_type IS '业务单据类型';
COMMENT ON COLUMN oa_flow.todo_item.title IS '待办标题';
COMMENT ON COLUMN oa_flow.todo_item.summary IS '待办摘要';
COMMENT ON COLUMN oa_flow.todo_item.applicant_user_id IS '申请人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.todo_item.applicant_name IS '申请人姓名快照';
COMMENT ON COLUMN oa_flow.todo_item.assignee_user_id IS '当前处理人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.todo_item.candidate_group IS '候选处理组标识';
COMMENT ON COLUMN oa_flow.todo_item.state IS '待办状态：PENDING、DONE 或 CANCELLED';
COMMENT ON COLUMN oa_flow.todo_item.org_id IS '单据发生时的组织主键快照';
COMMENT ON COLUMN oa_flow.todo_item.org_path IS '单据发生时的组织路径快照，用于数据权限过滤';
COMMENT ON COLUMN oa_flow.todo_item.created_at IS '待办创建时间';
COMMENT ON COLUMN oa_flow.todo_item.due_at IS '待办截止时间';
COMMENT ON COLUMN oa_flow.todo_item.finished_at IS '待办完成或取消时间';

COMMENT ON TABLE oa_flow.oa_outbox IS '事务发件箱，保证业务数据与待发布消息在同一事务提交';
COMMENT ON COLUMN oa_flow.oa_outbox.id IS '发件箱消息主键';
COMMENT ON COLUMN oa_flow.oa_outbox.topic IS 'Kafka 目标主题';
COMMENT ON COLUMN oa_flow.oa_outbox.msg_key IS 'Kafka 消息键';
COMMENT ON COLUMN oa_flow.oa_outbox.payload IS '序列化后的事件或命令载荷';
COMMENT ON COLUMN oa_flow.oa_outbox.status IS '投递状态：PENDING、SENT 或 FAILED';
COMMENT ON COLUMN oa_flow.oa_outbox.attempts IS '已尝试投递次数';
COMMENT ON COLUMN oa_flow.oa_outbox.next_attempt_at IS '下次允许重试的时间';
COMMENT ON COLUMN oa_flow.oa_outbox.last_error IS '最近一次投递失败原因';
COMMENT ON COLUMN oa_flow.oa_outbox.created_at IS '消息入箱时间';
COMMENT ON COLUMN oa_flow.oa_outbox.sent_at IS '消息成功投递时间';

COMMENT ON TABLE oa_flow.oa_inbox IS '事件收件箱，以 event_id 保证消费侧幂等';
COMMENT ON COLUMN oa_flow.oa_inbox.event_id IS '上游事件唯一标识';
COMMENT ON COLUMN oa_flow.oa_inbox.event_type IS '事件类型';
COMMENT ON COLUMN oa_flow.oa_inbox.consumed_at IS '首次成功消费时间';

COMMENT ON TABLE oa_flow.leave_type IS '假期类型目录及默认额度规则';
COMMENT ON COLUMN oa_flow.leave_type.id IS '假期类型主键';
COMMENT ON COLUMN oa_flow.leave_type.code IS '唯一假期类型编码';
COMMENT ON COLUMN oa_flow.leave_type.name IS '假期类型名称';
COMMENT ON COLUMN oa_flow.leave_type.paid IS '是否为带薪假';
COMMENT ON COLUMN oa_flow.leave_type.need_balance IS '请假时是否校验并扣减额度';
COMMENT ON COLUMN oa_flow.leave_type.max_days IS '单次或规则允许的最大天数';
COMMENT ON COLUMN oa_flow.leave_type.status IS '假期类型状态，默认 ACTIVE';

COMMENT ON TABLE oa_flow.leave_balance IS '用户按期间和假期类型维护的可用、已用与冻结额度';
COMMENT ON COLUMN oa_flow.leave_balance.id IS '假期余额主键';
COMMENT ON COLUMN oa_flow.leave_balance.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.leave_balance.user_id IS '用户 Casdoor sub';
COMMENT ON COLUMN oa_flow.leave_balance.leave_type_id IS '假期类型主键';
COMMENT ON COLUMN oa_flow.leave_balance.period IS '额度期间，通常为年份字符串';
COMMENT ON COLUMN oa_flow.leave_balance.total_days IS '期间授予总天数';
COMMENT ON COLUMN oa_flow.leave_balance.used_days IS '已正式消耗天数';
COMMENT ON COLUMN oa_flow.leave_balance.frozen_days IS '审批中的冻结天数';
COMMENT ON COLUMN oa_flow.leave_balance.version IS '乐观锁版本号';
COMMENT ON COLUMN oa_flow.leave_balance.updated_at IS '余额最后修改时间';

COMMENT ON TABLE oa_flow.leave_balance_txn IS '假期余额变动流水，以请求和动作联合去重';
COMMENT ON COLUMN oa_flow.leave_balance_txn.id IS '余额流水主键';
COMMENT ON COLUMN oa_flow.leave_balance_txn.balance_id IS '假期余额主键';
COMMENT ON COLUMN oa_flow.leave_balance_txn.request_id IS '请假单或额度操作的幂等业务标识';
COMMENT ON COLUMN oa_flow.leave_balance_txn.action IS '额度动作：FREEZE、CONSUME、RELEASE 或 GRANT';
COMMENT ON COLUMN oa_flow.leave_balance_txn.days IS '本次变动天数';
COMMENT ON COLUMN oa_flow.leave_balance_txn.remark IS '变动说明';
COMMENT ON COLUMN oa_flow.leave_balance_txn.created_at IS '流水创建时间';

COMMENT ON TABLE oa_flow.leave_request IS '带额度强一致语义的请假业务单据';
COMMENT ON COLUMN oa_flow.leave_request.id IS '请假单主键';
COMMENT ON COLUMN oa_flow.leave_request.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.leave_request.request_no IS '全局唯一请假单号';
COMMENT ON COLUMN oa_flow.leave_request.user_id IS '申请人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.leave_request.employee_id IS '申请人的员工内部主键';
COMMENT ON COLUMN oa_flow.leave_request.leave_type_id IS '假期类型主键';
COMMENT ON COLUMN oa_flow.leave_request.start_date IS '请假开始日期';
COMMENT ON COLUMN oa_flow.leave_request.end_date IS '请假结束日期';
COMMENT ON COLUMN oa_flow.leave_request.days IS '请假天数';
COMMENT ON COLUMN oa_flow.leave_request.reason IS '请假事由';
COMMENT ON COLUMN oa_flow.leave_request.status IS '单据状态：DRAFT、PENDING、APPROVED、REJECTED 或 CANCELLED';
COMMENT ON COLUMN oa_flow.leave_request.org_id IS '申请发生时的组织主键快照';
COMMENT ON COLUMN oa_flow.leave_request.org_path IS '申请发生时的组织路径快照，用于数据权限过滤';
COMMENT ON COLUMN oa_flow.leave_request.created_at IS '创建时间';
COMMENT ON COLUMN oa_flow.leave_request.decided_at IS '审批作出最终决定的时间';
COMMENT ON COLUMN oa_flow.leave_request.version IS '乐观锁版本号';

COMMENT ON TABLE oa_flow.business_doc IS '除请假外通用审批业务单据，差异字段保存在 form_data';
COMMENT ON COLUMN oa_flow.business_doc.id IS '通用业务单据主键';
COMMENT ON COLUMN oa_flow.business_doc.tenant_id IS '租户标识，当前默认租户为 1';
COMMENT ON COLUMN oa_flow.business_doc.biz_type IS '业务类型，如 TRAVEL、REIMBURSE、CONTRACT';
COMMENT ON COLUMN oa_flow.business_doc.doc_no IS '租户内唯一业务单号';
COMMENT ON COLUMN oa_flow.business_doc.applicant_id IS '申请人的 Casdoor sub';
COMMENT ON COLUMN oa_flow.business_doc.applicant_name IS '申请人姓名快照';
COMMENT ON COLUMN oa_flow.business_doc.title IS '单据标题';
COMMENT ON COLUMN oa_flow.business_doc.summary IS '单据摘要';
COMMENT ON COLUMN oa_flow.business_doc.form_data IS '按表单模板校验后的业务字段 JSON';
COMMENT ON COLUMN oa_flow.business_doc.amount IS '驱动审批级数与统计的金额字段';
COMMENT ON COLUMN oa_flow.business_doc.days IS '驱动审批级数与统计的天数字段';
COMMENT ON COLUMN oa_flow.business_doc.status IS '单据状态：PENDING、APPROVED、REJECTED 或 CANCELLED';
COMMENT ON COLUMN oa_flow.business_doc.org_id IS '申请发生时的组织主键快照';
COMMENT ON COLUMN oa_flow.business_doc.org_path IS '申请发生时的组织路径快照，用于数据权限过滤';
COMMENT ON COLUMN oa_flow.business_doc.created_at IS '创建时间';
COMMENT ON COLUMN oa_flow.business_doc.finished_at IS '审批结束时间';

COMMENT ON TABLE oa_flow.approval_level_rule IS '按业务类型配置审批级数的阈值规则';
COMMENT ON COLUMN oa_flow.approval_level_rule.biz_type IS '业务类型主键';
COMMENT ON COLUMN oa_flow.approval_level_rule.driver IS '定级驱动：DAYS、AMOUNT 或 FIXED';
COMMENT ON COLUMN oa_flow.approval_level_rule.thresholds IS '按顺序匹配的审批级数阈值 JSON 数组';
COMMENT ON COLUMN oa_flow.approval_level_rule.description IS '规则业务说明';
